export const SAT_API_KEY = "GH36MA-7XP7HB-GZJ4XQ-4SZV"
export const STARLINK_CATEGORY = "52"
export const NEARBY_SATELLITE = "rest/v1/satellite/above"
export const SATELLITE_POSITION_URL = "rest/v1/satellite/positions"
export const WORLD_MAP_URL = "https://unpkg.com/world-atlas@1/world/110m.json"
